### PR TITLE
split the restore section into 3 parts, and added a borgmatic section

### PR DESCRIPTION
**Pull request by meowmix3**
I'm new to Jekyll as well as git and had to look up the syntax, so please let me know how I can improve in the future.

### CODE REVIEW

**Comment by m3nu** [comment]
Cool. Give me a few hours to look over it.

**Comment by m3nu** [comment]
Just pulled in your changes. Writing is great. Content-wise, I'd change this:

#### `/restore`
- I would add a list and describe the different methods. Then disable the TOC. I think this overview page should give more details than just the TOC.

#### `/restore/fuse`
- I would rename this, since FUSE is just the library used. Maybe like "Mount and Browse Archive"?

#### `/restore/extract/ `
- Same here. You could do "extract" via Borgmatic or Vorta as well. So the differentiating thing is that we use the "Borg CLI". If we want a verb, maybe "Restore with Borg CLI" (short title) and "How to Restore Files from a Borg Backup Using the Borg CLI" (long title on page). Same for Borgmatic.
- I think this page could be expanded a bit to stand on its own: Add note about CLI usage (You should be comfortable using CLI...), add link on how to install Borg (`/linux/setup-borg-command-line/`), split into steps: 1) List and find archives, 2) Plan extraction/be in the right folder/`--strip components`.
- Could also link to the Borg docs for `extract` for more details.

#### `restore/borgmatic`
- Similar changes as for `extract`. "Restore with Borgmatic"
- Should link to the Borgmatic docs for more details and for install instructions.

I'm not fully sure about the short titles to use. "Restore" may be redundant, but since we can also "mount and browse" it, let's keep it. This would be the navigation:

```
Restore
- Mount and Browse Archive
- Restore with Borg CLI
- Restore with Borgmatic
```

Makes sense? What do you think?

**Comment by meowmix3** [comment]
All of those sound good to me, I'll work on them in coming days.  I had the same issue thinking of something to differentiate the title instead of "Restore" for the mount option , but your wording sounds great.

I'll do some rewriting and also draft up an overview that summarizes the other options, and adds some detail about taking precaution with restoring (in case of accidental overwrites).  Thanks for the comments!

**Comment by m3nu** [comment]
Hi, why close this PR? You can just push the next updates to the same branch and we keep the current discussion readily available.

**Comment by meowmix3** [comment]
> Hi, why close this PR? You can just push the next updates to the same branch and we keep the current discussion readily available.

My apologies, not super familiar with Github etiquette yet.  Noted

**Comment by m3nu** [comment]
No worries. I know the feeling..

**Comment by meowmix3** [comment]
Made all of the changes you recommended with a couple exceptions:
* I wasn't sure how to disable the ToC in Jekyll so I left that alone, although I don't think it looks that bad with it.
* Same for the Vorta page, not sure how to add external links in the navigation.

Jekyll has been pretty fun to play with though!  Much easier to use than I anticipated.

Please let me know what you think once you take a look at it.  I don't mind writing up the Restore page for Vorta as well once whenever we wrap this up.

**Comment by m3nu** [comment]
Hi Alex,

thanks for the contribution! I did some minor housekeeping and already merged it. You can view it here: https://docs.borgbase.com/restore/

If you like, we can add you as contributor. Either with full name or Github username.

Also, for the next PR, you can enable the checkbox "Allow commits by project contributors" (or similar). This allows me to push changes to your repo and work on changes together.

**Comment by meowmix3** [comment]
Of course, I'm glad to help. Thanks for being patient with me.

You can put my full name if you would like, its "Alexander Taylor".  

> Also, for the next PR, you can enable the checkbox "Allow commits by project contributors" (or similar). This allows me to push changes to your repo and work on changes together.

I was wondering about that, will do in the future.

**Pull request merged**
